name: Sync scriptlets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 1,5'

jobs:
  sync:
    name: Update scriptlets
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.repository_owner == 'ghostery'
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - name: Sync with upstream
        run: ./update.sh

      - uses: tibdex/github-app-token@v
        id: generate-token
        with:
          app_id: ${{ secrets.ADBLOCKERBOT_APP_ID }}
          private_key: ${{ secrets.ADBLOCKERBOT_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          committer: Ghostery Adblocker Bot <ghostery-adblocker-bot@users.noreply.github.com>
          author: Ghostery Adblocker Bot <ghostery-adblocker-bot@users.noreply.github.com>
          commit-message: "Update scriptlets"
          title: "Sync scriptlets with upstream"
          body: "Automated update of scriptlets."
          branch: sync-scriptlets

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
